Sys.setlocale('LC_ALL','Chinese_China.utf8')
raws <- c(lapply(1:255,as.raw), lapply(seq_len(94L*94L),function(i) as.raw(c((i-1L)%/%94L+161L,(i-1L)%%94L+161L))),
  lapply(161:223,function(i) as.raw(c(142L,i))),
  lapply(seq_len(94L*94L),function(i) as.raw(c(143L,(i-1L)%/%94L+161L,(i-1L)%%94L+161L))))
old <- iconv(vapply(raws,rawToChar,character(1)),from='EUC-JP',to='UTF-8')
new <- suppressWarnings(stringi::stri_encode(raws,from='EUC-JP',to='UTF-8'))
keep <- which(is.na(old) | old!=new)
keys <- vapply(raws[keep],function(x) sum(as.integer(x)*256^(rev(seq_along(x))-1L)),numeric(1))
groups <- split(keys,ifelse(is.na(old[keep]),'NA',vapply(stringi::stri_enc_toutf32(old[keep]),paste,character(1),collapse=',')))
out <- c('# Finite Windows EUC-JP compatibility delta, generated by',
  '# tools/performance/freeze_eucjp_compat.R. ICU performs tokenization/transcoding.',
  'appusage_text_eucjp_delta <- function() {','  list(')
for(i in seq_along(groups)) {
  x<-sort(groups[[i]])
  start<-c(1L,which(diff(x)!=1)+1L);end<-c(start[-1L]-1L,length(x))
  ranges<-vapply(seq_along(start),function(j) if(start[j]==end[j]) as.character(x[start[j]]) else paste0('seq.int(',x[start[j]],',',x[end[j]],')'),character(1))
  # One Unicode code point per valid mapping in this frozen converter.
  value<-if(names(groups)[i]=='NA') 'NA_integer_' else names(groups)[i]
  out<-c(out,paste0('    list(key = c(',paste(ranges,collapse=','),'), code = c(',value,'))',if(i<length(groups)) ',' else ''))
}
out<-c(out,'  )','}')
writeLines(out,'R/eucjp_compat.R')
cat(length(keys),'unit differences in',length(groups),'mapping groups\n')
