# Development-only oracle. Keep the ICU converter and record legacy differences.
Sys.setlocale('LC_ALL','Chinese_China.utf8')
raws <- lapply(1:255, as.raw)
text <- vapply(raws,rawToChar,character(1))
delta <- list()
for (encoding in iconvlist()) {
  info <- tryCatch(suppressWarnings(stringi::stri_enc_info(encoding)),error=function(e) NULL)
  if (is.null(info) || !identical(info$CharSize.max,1L)) next
  errors <- integer()
  old <- tryCatch(iconv(text,from=encoding,to='UTF-8'),error=function(e) {
    vapply(seq_along(text),function(i) tryCatch(iconv(text[[i]],from=encoding,to='UTF-8'),error=function(e) {
      errors <<- c(errors,i);NA_character_
    }),character(1))
  })
  new <- suppressWarnings(stringi::stri_encode(raws,from=encoding,to='UTF-8'))
  keep <- which(is.na(old) | is.na(new) | (!is.na(old) & !is.na(new) & old != new))
  if (length(keep)) delta[[toupper(encoding)]] <- list(byte=keep, code=stringi::stri_enc_toutf32(old[keep]), error=errors)
}
out <- c('# Frozen R 4.5.3 versus ICU single-byte converter deltas; generated by',
  '# tools/performance/freeze_sbcs_compat.R. Conversion remains in ICU.',
  'appusage_text_sbcs_mapping <- function() {',paste0('  ',capture.output(dput(delta)))[1L])
dump <- capture.output(dput(delta))
out <- c(out,paste0('  ',dump[-1L]),'}',
  'appusage_text_sbcs_delta <- local({', '  delta <- NULL',
  '  function(encoding) {', '    if (is.null(delta)) delta <<- appusage_text_sbcs_mapping()',
  '    delta[[encoding]]', '  }', '})')
writeLines(out,'R/encoding_compat.R')
cat(length(delta),'single-byte encoding aliases have compatibility deltas\n')
