# Build a reviewable compatibility delta against the frozen Windows R runtime.
# Production code uses only ICU; the base oracle is confined to development.
stopifnot(getRversion() == "4.5.3")
Sys.setlocale("LC_ALL", "Chinese_China.utf8")
code <- setdiff(seq.int(1L, 0x10ffff), c(seq.int(0xd800, 0xdfff),
  as.vector(outer(0:16 * 65536L, c(65534L, 65535L), `+`))))
chars <- stringi::stri_enc_fromutf32(as.list(code))
delta <- lapply(c("lower", "upper"), function(direction) {
  old <- if (direction == "lower") tolower(chars) else toupper(chars)
  new <- if (direction == "lower") stringi::stri_trans_tolower(chars, "en") else stringi::stri_trans_toupper(chars, "en")
  keep <- which(old != new)
  # Check the small delta in context so a leading BOM conversion quirk is not
  # incorrectly applied to an embedded BOM. Avoid millions of wrapped strings.
  wrapped <- stringi::stri_join("Q", chars[keep], "Q")
  old <- if (direction == "lower") tolower(wrapped) else toupper(wrapped)
  old <- stringi::stri_sub(old, 2L, -2L)
  different <- old != new[keep]
  list(from = code[keep[different]], to = stringi::stri_enc_toutf32(old[different]))
})
out <- c("# ICU full-case to frozen R 4.5.3 simple-case compatibility delta.",
  "# Generated by tools/performance/freeze_case_compat.R; no runtime base conversion.",
  "appusage_text_case_delta <- function(upper) {", "  if (upper) {")
out <- c(out, paste0("    ", capture.output(dput(delta[[2L]]))), "  } else {",
  paste0("    ", capture.output(dput(delta[[1L]]))), "  }", "}")
writeLines(out, "R/case_compat.R")
print(vapply(delta, function(x) length(x$from), integer(1)))
